### ISSUE TITLE
Method of obtaining the new credentials

### ISSUE THREAD

**Issue by andretunes** [SambasOnFire/VODAFONE-PT#1]
Hello! How are you?

I was wondering if you could share with me how did you get it, since I wanna update the credentials for the new ones.

Kind regards and stay safe,
André

**Comment by SambasOnFire** [comment]
Hi.
Follow this.
https://github.com/csersoft/hi_sd5115_openocd_config.
Jtag for SD5116H
https://blog.csersoft.net/archives/593

**Comment by andretunes** [comment]
Hello,

Thank you but without evolving opening the router is anything else?

SambasOnFire ***@***.***> escreveu no dia sábado, 10/04/2021
à(s) 23:12:
